using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UIFade : MonoBehaviour
{
    public Image fadeScreen;
    public float fadeSpeed;
    private bool shouldFadeToBlack;
    private bool shouldFadeFromBlack;
    private float timer;

    // Update is called once per frame
    void Update()
    {
        if (shouldFadeToBlack)
        {
            timer += Time.deltaTime;
            fadeScreen.color = new Color(fadeScreen.color.r, fadeScreen.color.g, fadeScreen.color.b, Mathf.MoveTowards(fadeScreen.color.a, 1f, fadeSpeed * timer));
            if(fadeScreen.color.a >= 1f) shouldFadeToBlack = false;
        }

        if (shouldFadeFromBlack)
        {
            timer += Time.deltaTime;
            fadeScreen.color = new Color(fadeScreen.color.r, fadeScreen.color.g, fadeScreen.color.b, Mathf.MoveTowards(fadeScreen.color.a, 0f, fadeSpeed * timer));
            if (fadeScreen.color.a <= 0f) shouldFadeFromBlack = false;
        }
    }

    public void FadeToBlack()
    {
        shouldFadeToBlack = true;
        shouldFadeFromBlack = false;
        timer = 0;
    }

    public void FadeFromBlack()
    {
        shouldFadeFromBlack = true;
        shouldFadeToBlack = false;
        timer = 0;
    }
}
